"""reports and asset snapshots

Revision ID: c4e8138aa39f
Revises: b10c9bf270f7
Create Date: 2026-08-27 16:28:36.027464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e8138aa39f'
down_revision: Union[str, Sequence[str], None] = 'b10c9bf270f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_by_user_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('computer_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(length=255), nullable=False),
    sa.Column('os_subtitle', sa.String(length=255), nullable=False),
    sa.Column('os_build', sa.String(length=100), nullable=False),
    sa.Column('cpu_name', sa.String(length=255), nullable=False),
    sa.Column('cpu_subtitle', sa.String(length=100), nullable=False),
    sa.Column('ram_total_gb', sa.Float(), nullable=False),
    sa.Column('disk_total_gb', sa.Float(), nullable=False),
    sa.Column('disk_used_gb', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('ram_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_snapshots_captured_at'), 'asset_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_captured_by_user_id'), 'asset_snapshots', ['captured_by_user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('computer_name', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(length=255), nullable=False),
    sa.Column('os_subtitle', sa.String(length=255), nullable=False),
    sa.Column('system_snapshot', sa.Text(), nullable=False),
    sa.Column('audit_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_asset_snapshots_captured_by_user_id'), table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_captured_at'), table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    # ### end Alembic commands ###
